version: '3.8'

services:
  flagsmith:
    build: .
    container_name: flagsmith
    ports:
      - "3000:3000"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:10.4.2  
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring
    restart: unless-stopped  
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  grafana-data: {}

networks:
  monitoring:
    driver: bridge
